Repository Archi7echs-Team/archi7echs-team.github.io, pull requests merged in 2024-11, with the labels that each got.

#8 prima stesura doc 2024-11-13
  documents/RTB/Verbali/Interni/2024-11-13.typ
Labels: V.I

#32 Prima stesura Piano di Progetto
  documents/RTB/Esterni/piano_di_progetto.typ
Labels: P.d.P

#33 creato NdP e diviso sezione, aggiornato template
  documents/RTB/Interni/NormeDiProgetto.typ
Labels: N.d.P

#35 Norme di Progetto: Scrittura sez. introduzione
  documents/RTB/Interni/NormeDiProgetto.typ
Labels: N.d.P

#41 Norme di Progetto: Una sezione di management e verifica documento
  documents/RTB/Interni/Norme di Progetto.typ
Labels: N.d.P

#46 prima stesura vi 2024-11-25
  documents/RTB/Interni/Verbali/2024-11-25.typ
Labels: V.I

#51 AdR - identificazione requisiti ed inizio sez req funzionali
  documents/RTB/Esterni/Analisi dei Requisiti.typ
Labels: A.d.R
