Repository Archi7echs-Team/archi7echs-team.github.io, pull requests merged in 2024-12, with the labels that each got.

#55 AdR - stesura caratteristiche utente
  documents/RTB/Esterni/Analisi dei Requisiti.typ
Labels: A.d.R

#57 prima stesura VI 2024-11-26
  documents/RTB/Interni/Verbali/2024-11-26.typ
Labels: V.I

#59 prima stesura VE 2024-11-26
  documents/RTB/Esterni/Verbali/2024-11-26.typ
Labels: V.E

#62 AdR - continuazione casi d'uso
  documents/RTB/Esterni/Analisi dei Requisiti.typ
Labels: A.d.R

#64 FIX AdR - aggiunto UC reperimento dati SQL
  documents/RTB/Esterni/Analisi dei Requisiti.typ
Labels: A.d.R, Fix

#68 Fix NdP: Verifica e Revisione della documentazione
  documents/RTB/Interni/Norme di Progetto.typ
Labels: N.d.P

#69 AdR - UC gestione errori
  documents/RTB/Esterni/Analisi dei Requisiti.typ
Labels: A.d.R

#70 NdP: redatta sezione assegnazione ruoli
  documents/RTB/Interni/Norme di Progetto.typ
Labels: N.d.P

#77 Prima stestura VI 2024-12-10
  documents/RTB/Interni/Verbali/2024-12-10.typ
Labels: V.I

#82 NdP - comunicazioni con proponente e strumenti
  documents/RTB/Interni/Norme di Progetto.typ
Labels: N.d.P

#89 NdP: Norme tipografiche e Regole sintattiche
  documents/RTB/Interni/Norme di Progetto.typ
Labels: N.d.P

#83 PdP - Stesura secondo periodo
  documents/RTB/Esterni/Piano di Progetto.typ
Labels: P.d.P

#76 prima stesura VE2024-12-09
  documents/RTB/Esterni/Verbali/2024-12-09.typ
Labels: V.E

#97 Riscritto l'UC5 nei due sotto casi d'uso
  documents/RTB/Esterni/Analisi dei Requisiti.typ
Labels: A.d.R

#109 AdR - Aggiunta sezione tecnologie + fix versioni
  documents/RTB/Esterni/Analisi dei Requisiti.typ
Labels: A.d.R, Fix

#105 Approvazione azienda verbale esterno 2024-12-09
  documents/RTB/Esterni/Verbali/2024-12-09.typ
Labels: V.E

#90 NdP - gestione dei processi
  documents/RTB/Interni/Norme di Progetto.typ
Labels: N.d.P

#108 PdQ - stesura introduzione
  documents/RTB/Esterni/Piano di Qualifica.typ
Labels: P.d.Q.

#110 NdP - sottosez. acronimi e abbreviazioni + ristrutturazione versionamento
  documents/RTB/Interni/Norme di Progetto.typ
Labels: N.d.P, Fix

#111 PdP - fix versioni tabella revisioni
  documents/RTB/Esterni/Piano di Progetto.typ
Labels: P.d.P, Fix

#107 Prima stestura VI 2024-12-17
  documents/RTB/Interni/Verbali/2024-12-17.typ
Labels: V.I

#112 Ristrutturazione generale del file e aggiunta di UC
  documents/RTB/Esterni/Analisi dei Requisiti.typ
Labels: A.d.R

#113 Fix percorsi e common
  documents/RTB/Esterni/Analisi dei Requisiti.typ
  documents/RTB/Esterni/Piano di Progetto.typ
  documents/RTB/Interni/Glossario.typ
  documents/RTB/Interni/Norme di Progetto.typ
  templates/allegato.typ
  templates/common.typ
  templates/documento.typ
Labels: Fix
