Repository Archi7echs-Team/archi7echs-team.github.io, pull requests merged in 2025-04, with the labels that each got.

#295 stesura periodo nove
  documents/PB/Esterni/Piano di Progetto.typ
Labels: P.d.P

#311 prima stesura VE04042025
  documents/PB/Esterni/Verbali/2025-04-04.typ
Labels: V.E

#312 prima stesura VI03042025
  documents/PB/Interni/Verbali/2025-04-03.typ
Labels: V.I

#313 stesura periodo 10
  documents/PB/Esterni/Piano di Progetto.typ
Labels: P.d.P

#320 prima stesura manuale utente
  documents/PB/Esterni/Manuale Utente.typ
  img/mu/avvio.jpg
  img/mu/camera.jpg
  img/mu/color.jpg
  img/mu/export.jpg
  img/mu/filter.jpg
  img/mu/gizmo.jpg
  img/mu/info.jpg
  img/mu/selectFilter.jpg
  img/mu/selection.jpg
  img/mu/settings.jpg
  img/mu/source.jpg
Labels: M.U

#321 ST - Sezione Architettura Deploy
  documents/PB/Esterni/Specifica Tecnica.typ
Labels: S.T

#324 Fix tecnologie e componenti front-end
  documents/PB/Esterni/Specifica Tecnica.typ
Labels: S.T

#322 aggiunta lettera di presentazione per PB
  documents/PB/Lettera di Presentazione.typ
Labels: Candidatura

#323 Aggiornamento AdR e PdQ - allineamento UC e requisiti, sistemazione numerazione
  documents/PB/Esterni/Analisi dei Requisiti.typ
  documents/PB/Esterni/Piano di Qualifica.typ
  img/adr/PB/11.png
  img/adr/PB/17.png
  img/adr/PB/18.png
  img/adr/PB/19.png
  img/adr/PB/20.png
  img/adr/PB/21.png
  img/adr/PB/22.png
  img/adr/PB/23.png
  img/adr/PB/27.png
  img/adr/PB/28.png
  img/adr/PB/29.png
  img/adr/PB/3.png
  img/adr/PB/30.png
  img/adr/PB/31.png
  img/adr/PB/32.png
  img/adr/PB/33.png
  img/adr/PB/34.png
  img/adr/PB/35.png
  img/adr/PB/36.png
  img/adr/PB/37.png
  img/adr/PB/38.png
  img/adr/PB/39.png
  img/adr/PB/4.png
  img/adr/PB/40.png
  img/adr/PB/41.png
  img/adr/PB/42.png
  img/adr/PB/43.png
  img/adr/PB/44.png
  img/adr/PB/45.png
  img/adr/PB/46.png
  img/adr/PB/47.png
  img/adr/PB/48.png
  img/adr/PB/49.png
  img/adr/PB/5.png
  img/adr/PB/6.png
  img/adr/PB/7.png
  img/adr/PB/8.png
  img/adr/PB/9.png
Labels: A.d.R

#330 Fix lettera di candidatura
  documents/PB/Lettera di Presentazione.typ
Labels: Candidatura, Fix

#333 Sito: Fix sezione riferimenti
  template.html
Labels: Agg_Sito, Fix

#338 prima stesura VI20250411
  documents/PB/Interni/Verbali/2025-04-03.typ
  documents/PB/Interni/Verbali/2025-04-11.typ
Labels: V.I

#344 prima stesura VI20250414
  documents/PB/Interni/Verbali/2025-04-14.typ
Labels: V.I

#350 PdP: Periodo 12 e Resoconto PB
  documents/PB/Esterni/Piano di Progetto.typ
Labels: P.d.P

#349 Glossario: aggiunta termini e definizioni
  documents/PB/Interni/Glossario.typ
Labels: Glossario

#354 PdQ - grafici e commenti metriche - fase PB
  documents/PB/Esterni/Piano di Qualifica.typ
  img/pdq/PB/MPC1.png
  img/pdq/PB/MPC12.png
  img/pdq/PB/MPC2-3.png
  img/pdq/PB/MPC4.png
  img/pdq/PB/MPC5.png
  img/pdq/PB/MPC6.png
  img/pdq/PB/MPC7.png
  img/pdq/PB/MPC8.png
  img/pdq/PB/MPC9.png
  img/pdq/PB/MPD1.png
  img/pdq/PB/MPD2.png
  img/pdq/PB/MPD3.png
  img/pdq/PB/MPD4.png
  img/pdq/PB/MPD8.png
Labels: P.d.Q.

#357 MU - Stesura API
  documents/PB/Esterni/Manuale Utente.typ
  documents/PB/Esterni/Specifica Tecnica.typ
  img/mu/downloadRelease.png
  img/mu/repoPage.png
  img/st/api.png
  img/st/csv.png
  img/st/db.png
Labels: M.U

#353 PdP: Verifica PB
  documents/PB/Esterni/Piano di Progetto.typ
Labels: P.d.P

#355 prima stesura VE20250415
  documents/PB/Esterni/Verbali/2025-04-04.typ
  documents/PB/Esterni/Verbali/2025-04-15.typ
Labels: V.E

#358 PdQ - revisione per PB e scatto versionamento
  documents/PB/Esterni/Piano di Qualifica.typ
Labels: P.d.Q.

#359 Fix glossario from RTB to PB
  .github/workflows/main.yml
Labels: Glossario

#361 Glossario: Verifica per PB
  documents/PB/Esterni/Piano di Qualifica.typ
  documents/PB/Interni/Glossario.typ
  img/pdq/PB/MPC12.png
Labels: Glossario

#362 Revisione Guida all'uso
  documents/PB/Esterni/Manuale Utente.typ
Labels: M.U
