Repository Archi7echs-Team/archi7echs-team.github.io, pull requests merged in 2025-02, with the labels that each got.

#194 Fix: Sezione contatti
  src/style.css
  template.html
Labels: Agg_Sito, Fix

#206 Fix font and sortBySurname in changelog
  templates/documento.typ
Labels: Fix

#204 Fix glossario caratteri speciali
  documents/RTB/Interni/Glossario.typ
  templates/documento.typ
Labels: Fix, Glossario

#201 Stesura del quinto periodo + sistemazione
  documents/RTB/Esterni/Piano di Progetto.typ
Labels: P.d.P

#216 prima stesura VI2025-01-30
  documents/RTB/Interni/Verbali/2025-01-30.typ
Labels: V.I

#207 PdQ - rif. grafana e grafici metriche
  documents/RTB/Esterni/Piano di Qualifica.typ
  img/pdq/MPC1.png
  img/pdq/MPC12.png
  img/pdq/MPC2-3.png
  img/pdq/MPC4.png
  img/pdq/MPC5.png
  img/pdq/MPC6.png
  img/pdq/MPC7.png
  img/pdq/MPC8.png
  img/pdq/MPC9.png
Labels: P.d.Q.

#217 Fix Sito: Aggiunta riferimenti
  src/style.css
  template.html
Labels: Agg_Sito, Fix

#219 NdP - revisione ortografica e sintattica
  documents/RTB/Interni/Norme di Progetto.typ
Labels: N.d.P, Fix

#221 Rimozione sezione stato dai verbali interni
  documents/RTB/Interni/Verbali/2024-11-13.typ
  documents/RTB/Interni/Verbali/2024-11-19.typ
  documents/RTB/Interni/Verbali/2024-11-25.typ
  documents/RTB/Interni/Verbali/2024-11-26.typ
  documents/RTB/Interni/Verbali/2024-12-04.typ
  documents/RTB/Interni/Verbali/2024-12-10.typ
  documents/RTB/Interni/Verbali/2024-12-17.typ
  documents/RTB/Interni/Verbali/2024-12-23.typ
  documents/RTB/Interni/Verbali/2025-01-07.typ
  documents/RTB/Interni/Verbali/2025-01-14.typ
  documents/RTB/Interni/Verbali/2025-01-22.typ
Labels: V.I, Fix

#225 PdP: revisione per RTB
  documents/RTB/Esterni/Piano di Progetto.typ
Labels: P.d.P

#223 revisione per RTB
  documents/RTB/Esterni/Piano di Qualifica.typ
Labels: P.d.Q.

#226 Scrittura lettera di candidatura per RTB
  documents/RTB/Esterni/Lettera candidatura RTB.typ
  documents/RTB/Interni/Norme di Progetto.typ
Labels: Candidatura

#220 revisione per RTB
  documents/RTB/Interni/Glossario.typ
  documents/RTB/Interni/Verbali/2025-01-30.typ
Labels: Glossario

#228 Fix asincronia versioni
  documents/RTB/Esterni/Piano di Progetto.typ
  img/pdq/MPC1.png
  img/pdq/MPC12.png
  img/pdq/MPC2-3.png
  img/pdq/MPC4.png
  img/pdq/MPC5.png
  img/pdq/MPC6.png
  img/pdq/MPC7.png
  img/pdq/MPC8.png
  img/pdq/MPC9.png
Labels: P.d.P, Fix, P.d.Q.
