Repository Archi7echs-Team/archi7echs-team.github.io, pull requests merged in 2025-03, with the labels that each got.

#239 Aggiunta consultivo aggiornato
  documents/PB/Esterni/Piano di Progetto.typ
Labels: P.d.P, Fix

#251 Fix indice
  documents/PB/Esterni/Piano di Progetto.typ
Labels: P.d.P, Fix

#248 NdP - fix metodo procedurale - stesura rif PB e sez. codifica: gest Git e Repo
  documents/PB/Interni/Norme di Progetto.typ
Labels: N.d.P, Fix

#241 Stesura verbale esterno
  documents/PB/Esterni/Verbali/2025-03-06.typ
Labels: V.E

#245 VI 2025-03-10
  documents/PB/Interni/Verbali/2025-03-10.typ
Labels: V.I

#255 Fixed plotst library
  .gitignore
  documents/PB/Esterni/Piano di Progetto.typ
  documents/PB/Esterni/Piano di Qualifica.typ
  documents/PB/Interni/Norme di Progetto.typ
  lib/plotst.typ
  lib/plotst/LICENSE
  lib/plotst/axis.typ
  lib/plotst/plotting.typ
  lib/plotst/util/classify.typ
  lib/plotst/util/util.typ
Labels: A.d.R, N.d.P, P.d.P, Fix, P.d.Q.

#254 Aggiunta analisi grafici
  documents/PB/Esterni/Piano di Qualifica.typ
Labels: P.d.Q.

#256 Stesura settimo periodo
  documents/PB/Esterni/Piano di Progetto.typ
Labels: P.d.P

#265 AdR: Fix tecnologie
  documents/PB/Esterni/Analisi dei Requisiti.typ
Labels: A.d.R, Fix

#266 Sito: Aggiunta riferimento repository MVP
  template.html
Labels: Agg_Sito

#267 NdP: Fix sezioni
  documents/PB/Interni/Norme di Progetto.typ
Labels: N.d.P, Fix

#268 VI 2025-03-17
  documents/PB/Interni/Verbali/2025-03-10.typ
  documents/PB/Interni/Verbali/2025-03-17.typ
Labels: V.I

#271 S.T. : Inizio stesura documento
  documents/PB/Esterni/Specifica Tecnica.typ
Labels: S.T

#270 PdP - stesura ottavo periodo
  documents/PB/Esterni/Piano di Progetto.typ
Labels: P.d.P

#269 VE-18-03
  documents/PB/Esterni/Verbali/2025-03-18.typ
Labels: V.E

#278 NdP - ampliamento sezione processi di supporto
  documents/PB/Interni/Norme di Progetto.typ
  documents/PB/Interni/Verbali/2025-03-17.typ
Labels: N.d.P
