Repository Archi7echs-Team/archi7echs-team.github.io, pull requests merged in 2025-01, with the labels that each got.

#123 V.E. 2024-12-23
  documents/RTB/Esterni/Verbali/2024-12-23.typ
Labels: V.E

#126 PdP - stesura sez terzo periodo
  documents/RTB/Esterni/Piano di Progetto.typ
Labels: P.d.P

#129 correz err ortografico
  documents/RTB/Interni/Norme di Progetto.typ
Labels: N.d.P, Fix

#145 NdP - Riorganizzazione di alcune sezioni del documento
  documents/RTB/Interni/Norme di Progetto.typ
Labels: N.d.P

#143 agg definizione di unita
  documents/RTB/Interni/Glossario.typ
Labels: Glossario

#148 Modifica UC
  documents/RTB/Esterni/Analisi dei Requisiti.typ
Labels: A.d.R, Fix

#158 Prima aggiunta UC
  img/adr/UC.drawio
Labels: A.d.R

#160 PdQ - obiettivi metrici qualità
  documents/RTB/Esterni/Piano di Qualifica.typ
Labels: P.d.Q.

#159 aggiunta UC 19 a 26
  documents/RTB/Esterni/Analisi dei Requisiti.typ
  img/adr/UC.drawio
Labels: A.d.R

#162 Fix tabella revisioni
  documents/RTB/Esterni/Piano di Progetto.typ
Labels: P.d.P, Fix

#169 Aggiunta metrica Cost Variance
  documents/RTB/Esterni/Piano di Qualifica.typ
  documents/RTB/Interni/Norme di Progetto.typ
Labels: N.d.P, P.d.Q.

#171 Aggiunte immagini diagrammi UC e aggiornate tabelle requisiti
  documents/RTB/Esterni/Analisi dei Requisiti.typ
  img/adr/UC 1.png
  img/adr/UC 10.png
  img/adr/UC 11.png
  img/adr/UC 12.png
  img/adr/UC 13.png
  img/adr/UC 14.png
  img/adr/UC 15.png
  img/adr/UC 16.png
  img/adr/UC 17.png
  img/adr/UC 18.png
  img/adr/UC 19.png
  img/adr/UC 2.png
  img/adr/UC 20.png
  img/adr/UC 21.png
  img/adr/UC 22.png
  img/adr/UC 23.png
  img/adr/UC 24.png
  img/adr/UC 25.png
  img/adr/UC 26.png
  img/adr/UC 2_1.png
  img/adr/UC 2_1_1.png
  img/adr/UC 2_1_2.png
  img/adr/UC 2_1_3.png
  img/adr/UC 2_2.png
  img/adr/UC 2_3.png
  img/adr/UC 2_4.png
  img/adr/UC 3.png
  img/adr/UC 4.png
  img/adr/UC 5.png
  img/adr/UC 6.png
  img/adr/UC 7.png
  img/adr/UC 8.png
  img/adr/UC 9.png
  img/adr/UC 9_1.png
  img/adr/UC 9_2.png
  img/adr/UC 9_3.png
  img/adr/UC 9_4.png
  img/adr/UC 9_5.png
Labels: A.d.R

#172 prima stesura 2025-01-14
  documents/RTB/Interni/Verbali/2025-01-14.typ
Labels: V.I

#180 prima stesura VI2025-01-22
  documents/RTB/Interni/Verbali/2025-01-22.typ
Labels: V.I

#181 prima stesura VE2025-01-24
  documents/RTB/Esterni/Verbali/2025-01-24.typ
Labels: V.E

#175 Modifiche UC e diagrammi UML
  documents/RTB/Esterni/Analisi dei Requisiti.typ
  img/adr/UC 1.png
  img/adr/UC 10.png
  img/adr/UC 11.png
  img/adr/UC 12.png
  img/adr/UC 13.png
  img/adr/UC 14.png
  img/adr/UC 15.png
  img/adr/UC 16.png
  img/adr/UC 17.png
  img/adr/UC 18.png
  img/adr/UC 19.png
  img/adr/UC 2.png
  img/adr/UC 20.png
  img/adr/UC 21.png
  img/adr/UC 22.png
  img/adr/UC 23.png
  img/adr/UC 24.png
  img/adr/UC 25.png
  img/adr/UC 26.png
  img/adr/UC 27.png
  img/adr/UC 2_1.png
  img/adr/UC 2_1_1.png
  img/adr/UC 2_1_2.png
  img/adr/UC 2_1_3.png
  img/adr/UC 2_2.png
  img/adr/UC 2_3.png
  img/adr/UC 2_4.png
  img/adr/UC 2_4_1.png
  img/adr/UC 3.png
  img/adr/UC 4.png
  img/adr/UC 5.png
  img/adr/UC 6.png
  img/adr/UC 7.png
  img/adr/UC 8.png
  img/adr/UC 9.png
  img/adr/UC 9_1.png
  img/adr/UC 9_2.png
  img/adr/UC 9_3.png
  img/adr/UC 9_4.png
  img/adr/UC 9_5.png
  img/adr/UC.drawio
Labels: A.d.R

#182 NdP - aggiunta sezioni
  documents/RTB/Interni/Norme di Progetto.typ
Labels: N.d.P

#184 Aggiornamento tabelle test
  documents/RTB/Esterni/Piano di Qualifica.typ
Labels: P.d.Q.
